--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 15.4

-- Started on 2023-10-02 17:15:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16508)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    number integer NOT NULL,
    balance double precision,
    creationdate date,
    accountstatus character varying(50),
    matricule character varying(8),
    code integer
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16544)
-- Name: account_number_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN number ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_number_seq
    START WITH 300
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16612)
-- Name: affectation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.affectation (
    startdate date,
    enddate date,
    employeematricule character varying(8),
    missioncode integer
);


ALTER TABLE public.affectation OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16467)
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    code integer NOT NULL,
    name character varying(30),
    prenoun character varying(30),
    birthdate date,
    phone character varying(11),
    adresse character varying(255)
);


ALTER TABLE public.client OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16543)
-- Name: client_code_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN code ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_code_seq
    START WITH 1000
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16523)
-- Name: currentaccount; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currentaccount (
    number integer NOT NULL,
    overdraft double precision
);


ALTER TABLE public.currentaccount OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16462)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    matricule character varying(8) NOT NULL,
    name character varying(30),
    prenoun character varying(30),
    birthdate date,
    phone character varying(11),
    hiringdate date,
    email character varying(50)
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16472)
-- Name: mission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mission (
    code integer NOT NULL,
    name character varying(50),
    description character varying(255)
);


ALTER TABLE public.mission OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16611)
-- Name: mission_code_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mission ALTER COLUMN code ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mission_code_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16595)
-- Name: operation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operation (
    number integer NOT NULL,
    creationdate date,
    montant double precision,
    typeoperation character varying(50),
    employeematricule character varying(8),
    accountnumber integer
);


ALTER TABLE public.operation OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16610)
-- Name: operation_number_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.operation ALTER COLUMN number ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_number_seq
    START WITH 1000
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16513)
-- Name: savingaccount; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.savingaccount (
    number integer NOT NULL,
    interestrate double precision
);


ALTER TABLE public.savingaccount OWNER TO postgres;

--
-- TOC entry 3373 (class 0 OID 16508)
-- Dependencies: 217
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account (number, balance, creationdate, accountstatus, matricule, code) FROM stdin;
300	44	2023-09-26	ACTIF	\N	\N
302	22	2023-09-26	ACTIF	\N	\N
303	22	2023-09-26	ACTIF	\N	\N
306	11	2023-09-26	ACTIF	\N	\N
308	55	2023-09-26	ACTIF	\N	\N
310	905	2023-09-27	INACTIF	MUDPJ985	1001
\.


--
-- TOC entry 3381 (class 0 OID 16612)
-- Dependencies: 225
-- Data for Name: affectation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.affectation (startdate, enddate, employeematricule, missioncode) FROM stdin;
2023-10-02	2023-10-03	MUDPJ985	1
\.


--
-- TOC entry 3371 (class 0 OID 16467)
-- Dependencies: 215
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client (code, name, prenoun, birthdate, phone, adresse) FROM stdin;
1001	SAMIR	NAIM	2000-05-06	062264321	SAFI MATAR
1000	KARIMA	BENJELLOUN	2000-10-09	9876	UGUI
1002	SALMA	MRNISI	1999-09-07	0854322	QUATAR
\.


--
-- TOC entry 3375 (class 0 OID 16523)
-- Dependencies: 219
-- Data for Name: currentaccount; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.currentaccount (number, overdraft) FROM stdin;
300	44
302	22
303	33
308	77
310	10
\.


--
-- TOC entry 3370 (class 0 OID 16462)
-- Dependencies: 214
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (matricule, name, prenoun, birthdate, phone, hiringdate, email) FROM stdin;
Z2IW6QO2	lamiae	BOURICH	2001-07-05	06758392	2023-09-25	LAMIA@gmail.com
MUDPJ985	KAMAL	HARITE	2001-11-11	0943221	2023-09-25	KAMALI@gmail.com
\.


--
-- TOC entry 3372 (class 0 OID 16472)
-- Dependencies: 216
-- Data for Name: mission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mission (code, name, description) FROM stdin;
1	account manager	in charge of creating clients accounts and transfert
\.


--
-- TOC entry 3378 (class 0 OID 16595)
-- Dependencies: 222
-- Data for Name: operation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operation (number, creationdate, montant, typeoperation, employeematricule, accountnumber) FROM stdin;
1001	2023-10-01	10	PAYEMENT	Z2IW6QO2	310
1002	2023-10-01	10	PAYEMENT	MUDPJ985	310
1003	2023-10-01	5	WITHDRAW	MUDPJ985	310
\.


--
-- TOC entry 3374 (class 0 OID 16513)
-- Dependencies: 218
-- Data for Name: savingaccount; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.savingaccount (number, interestrate) FROM stdin;
306	11
\.


--
-- TOC entry 3387 (class 0 OID 0)
-- Dependencies: 221
-- Name: account_number_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_number_seq', 310, true);


--
-- TOC entry 3388 (class 0 OID 0)
-- Dependencies: 220
-- Name: client_code_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_code_seq', 1002, true);


--
-- TOC entry 3389 (class 0 OID 0)
-- Dependencies: 224
-- Name: mission_code_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mission_code_seq', 2, true);


--
-- TOC entry 3390 (class 0 OID 0)
-- Dependencies: 223
-- Name: operation_number_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operation_number_seq', 1003, true);


--
-- TOC entry 3211 (class 2606 OID 16512)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (number);


--
-- TOC entry 3207 (class 2606 OID 16471)
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (code);


--
-- TOC entry 3215 (class 2606 OID 16527)
-- Name: currentaccount currentaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currentaccount
    ADD CONSTRAINT currentaccount_pkey PRIMARY KEY (number);


--
-- TOC entry 3205 (class 2606 OID 16466)
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (matricule);


--
-- TOC entry 3209 (class 2606 OID 16476)
-- Name: mission mission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mission
    ADD CONSTRAINT mission_pkey PRIMARY KEY (code);


--
-- TOC entry 3217 (class 2606 OID 16599)
-- Name: operation operation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT operation_pkey PRIMARY KEY (number);


--
-- TOC entry 3213 (class 2606 OID 16517)
-- Name: savingaccount savingaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.savingaccount
    ADD CONSTRAINT savingaccount_pkey PRIMARY KEY (number);


--
-- TOC entry 3218 (class 2606 OID 16565)
-- Name: account account_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_code_fkey FOREIGN KEY (code) REFERENCES public.client(code) ON DELETE CASCADE;


--
-- TOC entry 3219 (class 2606 OID 16570)
-- Name: account account_matricule_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_matricule_fkey FOREIGN KEY (matricule) REFERENCES public.employee(matricule) ON DELETE SET NULL;


--
-- TOC entry 3226 (class 2606 OID 16615)
-- Name: affectation affectation_employeematricule_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.affectation
    ADD CONSTRAINT affectation_employeematricule_fkey FOREIGN KEY (employeematricule) REFERENCES public.employee(matricule) ON DELETE SET NULL;


--
-- TOC entry 3227 (class 2606 OID 16620)
-- Name: affectation affectation_missioncode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.affectation
    ADD CONSTRAINT affectation_missioncode_fkey FOREIGN KEY (missioncode) REFERENCES public.mission(code) ON DELETE SET NULL;


--
-- TOC entry 3223 (class 2606 OID 16550)
-- Name: currentaccount currentaccount_number_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currentaccount
    ADD CONSTRAINT currentaccount_number_fkey FOREIGN KEY (number) REFERENCES public.account(number) ON DELETE CASCADE;


--
-- TOC entry 3220 (class 2606 OID 16560)
-- Name: account fk_client; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fk_client FOREIGN KEY (code) REFERENCES public.client(code);


--
-- TOC entry 3221 (class 2606 OID 16555)
-- Name: account fk_employee; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fk_employee FOREIGN KEY (matricule) REFERENCES public.employee(matricule);


--
-- TOC entry 3224 (class 2606 OID 16600)
-- Name: operation operation_accountnumber_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT operation_accountnumber_fkey FOREIGN KEY (accountnumber) REFERENCES public.account(number);


--
-- TOC entry 3225 (class 2606 OID 16605)
-- Name: operation operation_employeematricule_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT operation_employeematricule_fkey FOREIGN KEY (employeematricule) REFERENCES public.employee(matricule);


--
-- TOC entry 3222 (class 2606 OID 16545)
-- Name: savingaccount savingaccount_number_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.savingaccount
    ADD CONSTRAINT savingaccount_number_fkey FOREIGN KEY (number) REFERENCES public.account(number) ON DELETE CASCADE;


-- Completed on 2023-10-02 17:15:24

--
-- PostgreSQL database dump complete
--

